---
# tasks file for roles/osp-facter

- name: fetch instance info
  os_server_facts:
   cloud: "{{ item.cloud }}"
   region_name: "{{ item.region_name }}"
  with_items: "{{ osp_facter__cloud_region }}"
  register: osp_facter__os_server_facts_results

- name: add host to inventory
  add_host:
   name: "{{ item.1.public_v4 }}"
   group: "{{ item.1.metadata.group }}"
  with_subelements:
    - "{{ osp_facter__os_server_facts_results.results }}"
    - ansible_facts.openstack_servers
  loop_control:
    label: "{{ item.1.metadata.group + ' ' + item.1.public_v4 }}"

