- name: provision OpenStack networks, ssh keys, flavors, security groups
  hosts: jumpbox
  become: yes

  roles:
    - role: osp-workstation
      tags: [ workstation ]

    - role: osp-net
      tags: [ network ]

    - role: osp-key
      tags: [ key ]

    - role: osp-flavor
      tags: [ flavor ]

    - role: osp-sg
      tags: [ sg ]

    - role: osp-instance
      tags: [ instance ]

    - role: osp-facter
      tags: [ inventory ]

