- name: provision OpenStack networks, ssh keys, flavors, security groups
  hosts: jumpbox
  become: no

  roles:
    - role: osp-net
      osp_net__networks:
        - type: os_network
          cloud: ospcloud
          state: present
          name: ext_network
          external: true
        - type: os_subnet
          cloud: ospcloud
          state: present
          network_name: ext_network
          name: external_subnet
          cidr: 10.10.10.0/24
          dns_nameservers:
            - 8.8.8.7
            - 8.8.8.8
          host_routes:
            - destination: 0.0.0.0/0
              nexthop: 10.10.10.0
            - destination: 192.168.0.0/24
              nexthop: 192.168.0.0
        - type: os_network
          cloud: ospcloud
          state: present
          name: int_network
          external: false
        - type: os_subnet
          cloud: ospcloud
          state: present
          network_name: int_network
          name: int_subnet
          cidr: 20.20.20.0/24
          dns_nameservers:
            - 8.8.8.7
            - 8.8.8.8
          host_routes:
            - destination: 0.0.0.0/0
              nexthop: 192.168.0.0
            - destination: 192.168.0.0/24
              nexthop: 192.168.0.0
        - type: os_router
          cloud: ospcloud
          state: present
          name: router1
          network: ext_network
          external_fixed_ips:
            - subnet: external_subnet
          interfaces:
            - int_subnet
      tags:
        - network

    - role: osp-key
      osp_key__ssh_keys:
        - username: "{{ ansible_env.USER }}"
          file: "{{ ansible_env.HOME + '/.ssh/ansible_ssh' }}"
          cloud: ospcloud
          state: present
      tags:
        - key

    - role: osp-flavor
      osp_flavor__flavors:
        - cloud: ospcloud
          state: present
          name: m2.small
          ram: 2048
          vcpus: 1
          disk: 10
      tags:
        - flavor

    - role: osp-sg
      osp_sg__sgs:
        - cloud: ospcloud
          state: present
          name: app_servers
          description: ports_open
          protocol: tcp
          rules:
            - { port: '8080', ip_prefix: '0.0.0.0/0' }
            - { port: '22', ip_prefix: '0.0.0.0/0' }
        - cloud: ospcloud
          state: present
          name: frontend_servers
          description: ports_open
          protocol: tcp
          rules:
            - { port: '80', ip_prefix: '0.0.0.0/0' }
            - { port: '443', ip_prefix: '0.0.0.0/0' }
            - { port: '22', ip_prefix: '0.0.0.0/0' }
        - cloud: ospcloud
          state: present
          name: db_servers
          description: ports_open
          protocol: tcp
          rules:
            - { port: '5432', ip_prefix: '20.20.20.0/24' }
            - { port: '22', ip_prefix: '0.0.0.0/0' }
      tags:
        - sg

    - role: osp-instance
      osp_instance__template:
        cloud: ospcloud
        state: present
        image: rhel-guest
        deployment: dev
        flavor: m2.small
        key_name: ansible_ssh
        nics:
          - net-name: int_network
        userdata: |
          #!/bin/bash
          curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
          cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
          curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
          cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
        ext_network: ext_network
        wait: no
      osp_instance__instances:
        - name: frontend
          group: frontends
          security_groups: frontend_servers
        - name: app1
          group: apps
          security_groups: app_servers
        - name: app2
          group: apps
          security_groups: app_servers
        - name: db
          group: appdbs
          security_groups: db_servers
      tags:
        - instance

