---
# defaults file for roles/osp-sg

osp_sg__sgs: []
# Example of osp_sg__sgs structure
# osp_sg__sgs:
#   - cloud: ospcloud
#     state: present
#     name: app_servers
#     description: ports_open
#     protocol: tcp
#     rules:
#       - { port: '8080', ip_prefix: '0.0.0.0/0' }
#       - { port: '22', ip_prefix: '0.0.0.0/0' }
#   - cloud: ospcloud
#     state: present
#     name: frontend_servers
#     description: ports_open
#     protocol: tcp
#     rules:
#       - { port: '80', ip_prefix: '0.0.0.0/0' }
#       - { port: '443', ip_prefix: '0.0.0.0/0' }
#       - { port: '22', ip_prefix: '0.0.0.0/0' }
#   - cloud: ospcloud
#     state: present
#     name: db_servers
#     description: ports_open
#     protocol: tcp
#     rules:
#       - { port: '5432', ip_prefix: '20.20.20.0/24' }
#       - { port: '22', ip_prefix: '0.0.0.0/0' }
#
